### ISSUE TITLE
Breaking changes in 24.1

### ISSUE THREAD

**Issue by th3voic3** [dblanque/opnsense-zabbix#1]
Hi,

I really like this template first of all. 
In 24.1 the function get_interfaces_info was removed breaking the opnsense_zbx.php script.

**Comment by dblanque** [comment]
Oof, that's a bummer...

I haven't implemented version 24.1 in any environment yet, any idea if this function was only re-named/re-implemented or was it fully deleted from OPNSense?

Thanks,
Dylan

**Comment by th3voic3** [comment]
I'm not really sure yet if there is an adequate replacement. 

The function was removed in this commit:
https://github.com/opnsense/core/commit/4d495ea6cc3d3c993662867bf3b3a072069e1fc8

**Comment by dblanque** [comment]
Thank you so much for finding that, I appreciate it.
From what I could check `get_interface_list` and `get_interfaces_info` might be related but I'm not entirely sure they give the required/same info.
I'll check it out as soon as I have that version available on a host.

**Comment by dblanque** [comment]
@th3voic3 Please let me know if it's working for you now!
I also went ahead and added a small fix in the Network Discovery function to check for strlen (Empty interface name detected bug).

**Comment by th3voic3** [comment]
@dblanque looking good. Thanks for the quick fix and I'm honored for being mentioned in the code :)

**Comment by dblanque** [comment]
No problem! Lemme know if you find any more issues.
I updated the YAML Templates by the way with some more statistic goodies for the auto-discoverable interfaces.
Cheers!
