### ISSUE TITLE
Function undefined get_ppp_parent() in opnsense_zbx.php on line 178

### ISSUE THREAD

**Issue by julioliraup** [dblanque/opnsense-zabbix#10]
Hi, in new commit test, see this error  
![image](https://github.com/user-attachments/assets/6cc9681a-9b92-44b0-92d7-c5cfc890a466)

**Comment by dblanque** [comment]
This is unrelated to the latest commit, but rather the codebase for OPNSense loosing or changing this function's name for some reason. The issue is being worked on.

**Comment by dblanque** [comment]
What version of OPNSense are you using? Is it STABLE?

**Comment by dblanque** [comment]
I don't really have any way to test it, as the current stable version installations we use still contain the `get_ppp_parent` function, but feel free to test the newest commit out and let me know if the results are correct. 

For reference the file containing both functions in the OPNSense source is `/usr/local/etc/inc/interfaces.inc` or [/src/etc/inc/interfaces.inc (click here to open Git source)](https://github.com/opnsense/core/blob/master/src/etc/inc/interfaces.inc)

Thank you for contributing and reporting problems, always appreciated :)

**Comment by julioliraup** [comment]
I see: Version 	24.7.6 (stable)
I try check error and add here, thnx for response!

**Comment by dblanque** [comment]
I have tested the latest commit on a fresh/clean install of 24.7 and 24.7.7.

Please let me know if it works for you and I'll close the issue.
![Screenshot_20241025_161035](https://github.com/user-attachments/assets/98c0a32a-0177-48b0-9b60-c7c6812260c2)

Regards,
Dylan

**Comment by julioliraup** [comment]
I couldn't test it, I'll close it, if the error occurs again I'll reopen it ok?
