### ISSUE TITLE
error to add template a host

### ISSUE THREAD

**Issue by burghy86** [dblanque/opnsense-zabbix#2]
when add opnsense active template to host, i have this error:

Cannot inherit item prototype with key "net.if.in[{#IFNAME}]" of template "Template OPNSense Active" and LLD rule "Network interface discovery" to host "opnarcobaleno", because an item prototype with the same key already belongs to LLD rule "Network interface discovery".

**Comment by dblanque** [comment]
Hi burghy, what version of Zabbix are you using? Have you tried deleting the Template and re-creating it?
