### ISSUE TITLE
guide integration

### ISSUE THREAD

**Issue by burghy86** [dblanque/opnsense-zabbix#4]
in a readme guide you are forget to insert:

First copy the file opnsense_zbx.php to your opnsense box (e.g. to /root/scripts)
connect with ssh on opnsense and send this command:
`curl --create-dirs -o /root/scripts/pfsense_zbx.php https://raw.githubusercontent.com/dblanque/opnsense-zabbix/main/opnsense_zbx.php`

**Comment by dblanque** [comment]
Thank you for noticing that Burghy!
Fixed and updated README.md with the correct script name (`opnsense_zbx.php`) on Commit 58cd6e3
