### ISSUE TITLE
host with passive not work

### ISSUE THREAD

**Issue by burghy86** [dblanque/opnsense-zabbix#5]
is normal the host is unknow?
![immagine](https://github.com/dblanque/opnsense-zabbix/assets/17832100/373417be-9b87-4171-b46a-198f291e0faa)

and using a classic freebsd template work?
![immagine](https://github.com/dblanque/opnsense-zabbix/assets/17832100/9d4e2a84-6530-486b-a6b1-9946fa88f0e8)

**Comment by dblanque** [comment]
You're using a different IP address on one node and the other. Check that the Firewall is accepting and allowing connections on the Zabbix Port (default 10050) and that the service is running, not much more than that to it. The README in the repo has all the info you need to install it.

This is not a Script/Template problem, marking as closed.
Cheers!

**Comment by burghy86** [comment]
Excuse me.  Yes, I sent you two screens of two different opns for your convenience.  I also tested it on the same host by changing the template.  same result.

**Comment by dblanque** [comment]
Zabbix Agent Status is not affected at all by this template. If it doesn't work on a specific instance of yours, **check your firewall** and **Zabbix Agent settings**.
Check the instructions and see if you missed any steps. The template works.

- Have you checked the logs for any errors?
- Do you have the script downloaded locally on `/root/scripts`?
- Did you add the required keys to your Zabbix Agent configuration (either through GUI or a `.conf` file)?
- Have you tried setting `AllowRoot=1`?
- Have you tried running the Zabbix Agent with Allow Sudo (GUI) ON?
