### ISSUE TITLE
Template Zabbix

### ISSUE THREAD

**Issue by marcellomarques1986** [dblanque/opnsense-zabbix#7]
Hello,

First, I would like to thank you for your contribution.

I followed the configuration recommendations, but the items are not being collected, only the SNMP data is coming, the discovery does not work.

My need is to monitor gateways and IPsec

**Comment by dblanque** [comment]
The template works, we are currently using it in multiple production environments, so I'd recommend that you re-check the instructions and see that everything is setup properly. Make sure you've setup the correct **ACTIVE Zabbix Server/Proxy IP** in your _Zabbix Features_ tab.

IPSec Monitoring is not tested/supported.
